const airports = [
    "Budapest", "Debrecen", "New York", "London", "Paris", "Berlin", "Madrid", "Los Angeles", 
    "Rome", "Milan", "Barcelona", "Amsterdam", "Vienna", "Frankfurt", "Lisbon", "Copenhagen", 
    "Stockholm", "Warsaw", "Prague", "Zurich", "Brussels", "Dubai", "Istanbul", "Athens", "Oslo", "Helsinki"
];

const departureSelect = document.getElementById("departure");
const arrivalSelect = document.getElementById("arrival");

airports.forEach(airport => {
    const option = document.createElement("option");
    option.value = airport;
    option.textContent = airport;
    departureSelect.appendChild(option);
    arrivalSelect.appendChild(option.cloneNode(true));
});

const flightData = {
    "Budapest_Debrecen": { duration: "0h 50m" },
    "Budapest_New York": { duration: "9h 30m" },
    "Budapest_London": { duration: "2h 30m" },
    "Budapest_Paris": { duration: "2h 15m" },
    "Budapest_Berlin": { duration: "1h 45m" },
    "Budapest_Madrid": { duration: "3h 15m" },
    "Budapest_Los Angeles": { duration: "13h 15m" },
    "Budapest_Rome": { duration: "1h 50m" },
    "Budapest_Milan": { duration: "1h 40m" },
    "Budapest_Barcelona": { duration: "2h 50m" },
    "Budapest_Amsterdam": { duration: "2h 10m" },
    "Budapest_Vienna": { duration: "0h 45m" },
    "Budapest_Frankfurt": { duration: "1h 40m" },
    "Budapest_Lisbon": { duration: "3h 30m" },
    "Budapest_Copenhagen": { duration: "2h 0m" },
    "Budapest_Stockholm": { duration: "2h 10m" },
    "Budapest_Warsaw": { duration: "1h 10m" },
    "Budapest_Prague": { duration: "1h 0m" },
    "Budapest_Zurich": { duration: "1h 50m" },
    "Budapest_Brussels": { duration: "2h 0m" },
    "Budapest_Dubai": { duration: "5h 50m" },
    "Budapest_Istanbul": { duration: "2h 5m" },
    "Budapest_Athens": { duration: "2h 0m" },
    "Budapest_Oslo": { duration: "2h 20m" },
    "Budapest_Helsinki": { duration: "2h 25m" },

    "Debrecen_Budapest": { duration: "0h 50m" },
    "Debrecen_New York": { duration: "9h 45m" },
    "Debrecen_London": { duration: "2h 40m" },
    "Debrecen_Paris": { duration: "2h 30m" },
    "Debrecen_Berlin": { duration: "1h 50m" },
    "Debrecen_Madrid": { duration: "3h 20m" },
    "Debrecen_Los Angeles": { duration: "13h 30m" },
    "Debrecen_Rome": { duration: "2h 0m" },
    "Debrecen_Milan": { duration: "1h 50m" },
    "Debrecen_Barcelona": { duration: "3h 0m" },
    "Debrecen_Amsterdam": { duration: "2h 20m" },
    "Debrecen_Vienna": { duration: "0h 55m" },
    "Debrecen_Frankfurt": { duration: "1h 50m" },
    "Debrecen_Lisbon": { duration: "3h 40m" },
    "Debrecen_Copenhagen": { duration: "2h 10m" },
    "Debrecen_Stockholm": { duration: "2h 30m" },
    "Debrecen_Warsaw": { duration: "1h 20m" },
    "Debrecen_Prague": { duration: "1h 10m" },
    "Debrecen_Zurich": { duration: "2h 0m" },
    "Debrecen_Brussels": { duration: "2h 10m" },
    "Debrecen_Dubai": { duration: "6h 0m" },
    "Debrecen_Istanbul": { duration: "2h 20m" },
    "Debrecen_Athens": { duration: "2h 10m" },
    "Debrecen_Oslo": { duration: "2h 30m" },
    "Debrecen_Helsinki": { duration: "2h 40m" },

    "New York_Budapest": { duration: "8h 30m" },
    "New York_Debrecen": { duration: "9h 0m" },
    "New York_London": { duration: "7h 0m" },
    "New York_Paris": { duration: "7h 15m" },
    "New York_Berlin": { duration: "7h 40m" },
    "New York_Madrid": { duration: "7h 45m" },
    "New York_Los Angeles": { duration: "6h 15m" },
    "New York_Rome": { duration: "8h 20m" },
    "New York_Milan": { duration: "8h 10m" },
    "New York_Barcelona": { duration: "7h 50m" },
    "New York_Amsterdam": { duration: "7h 30m" },
    "New York_Vienna": { duration: "8h 25m" },
    "New York_Frankfurt": { duration: "7h 35m" },
    "New York_Lisbon": { duration: "7h 45m" },
    "New York_Copenhagen": { duration: "7h 50m" },
    "New York_Stockholm": { duration: "8h 0m" },
    "New York_Warsaw": { duration: "8h 10m" },
    "New York_Prague": { duration: "8h 20m" },
    "New York_Zurich": { duration: "8h 15m" },
    "New York_Brussels": { duration: "7h 40m" },
    "New York_Dubai": { duration: "12h 45m" },
    "New York_Istanbul": { duration: "10h 50m" },
    "New York_Athens": { duration: "10h 15m" },
    "New York_Oslo": { duration: "8h 30m" },
    "New York_Helsinki": { duration: "8h 40m" },

    "London_Budapest": { duration: "2h 30m" },
    "London_Debrecen": { duration: "2h 45m" },
    "London_New York": { duration: "7h 30m" },
    "London_Paris": { duration: "1h 15m" },
    "London_Berlin": { duration: "1h 50m" },
    "London_Madrid": { duration: "2h 20m" },
    "London_Los Angeles": { duration: "11h 0m" },
    "London_Rome": { duration: "2h 40m" },
    "London_Milan": { duration: "1h 55m" },
    "London_Barcelona": { duration: "2h 10m" },
    "London_Amsterdam": { duration: "1h 20m" },
    "London_Vienna": { duration: "2h 10m" },
    "London_Frankfurt": { duration: "1h 40m" },
    "London_Lisbon": { duration: "2h 45m" },
    "London_Copenhagen": { duration: "1h 55m" },
    "London_Stockholm": { duration: "2h 20m" },
    "London_Warsaw": { duration: "2h 30m" },
    "London_Prague": { duration: "2h 10m" },
    "London_Zurich": { duration: "1h 50m" },
    "London_Brussels": { duration: "1h 10m" },
    "London_Dubai": { duration: "7h 0m" },
    "London_Istanbul": { duration: "4h 0m" },
    "London_Athens": { duration: "3h 50m" },
    "London_Oslo": { duration: "2h 10m" },
    "London_Helsinki": { duration: "2h 50m" },


    "Paris_Budapest": { duration: "2h 30m" },
    "Paris_Debrecen": { duration: "2h 45m" },
    "Paris_New York": { duration: "8h 30m" },
    "Paris_London": { duration: "1h 15m" },
    "Paris_Berlin": { duration: "1h 45m" },
    "Paris_Madrid": { duration: "2h 0m" },
    "Paris_Los Angeles": { duration: "11h 0m" },
    "Paris_Rome": { duration: "2h 10m" },
    "Paris_Milan": { duration: "1h 45m" },
    "Paris_Barcelona": { duration: "1h 50m" },
    "Paris_Amsterdam": { duration: "1h 20m" },
    "Paris_Vienna": { duration: "1h 50m" },
    "Paris_Frankfurt": { duration: "1h 30m" },
    "Paris_Lisbon": { duration: "2h 30m" },
    "Paris_Copenhagen": { duration: "1h 45m" },
    "Paris_Stockholm": { duration: "2h 10m" },
    "Paris_Warsaw": { duration: "2h 20m" },
    "Paris_Prague": { duration: "1h 45m" },
    "Paris_Zurich": { duration: "1h 30m" },
    "Paris_Brussels": { duration: "1h 10m" },
    "Paris_Dubai": { duration: "7h 30m" },
    "Paris_Istanbul": { duration: "3h 20m" },
    "Paris_Athens": { duration: "3h 0m" },
    "Paris_Oslo": { duration: "2h 10m" },
    "Paris_Helsinki": { duration: "2h 50m" },

    "Berlin_Budapest": { duration: "1h 30m" },
    "Berlin_Debrecen": { duration: "2h 0m" },
    "Berlin_New York": { duration: "9h 0m" },
    "Berlin_London": { duration: "1h 45m" },
    "Berlin_Paris": { duration: "1h 30m" },
    "Berlin_Madrid": { duration: "2h 30m" },
    "Berlin_Los Angeles": { duration: "11h 0m" },
    "Berlin_Rome": { duration: "2h 0m" },
    "Berlin_Milan": { duration: "1h 30m" },
    "Berlin_Barcelona": { duration: "2h 0m" },
    "Berlin_Amsterdam": { duration: "1h 15m" },
    "Berlin_Vienna": { duration: "1h 30m" },
    "Berlin_Frankfurt": { duration: "1h 0m" },
    "Berlin_Lisbon": { duration: "3h 0m" },
    "Berlin_Copenhagen": { duration: "1h 30m" },
    "Berlin_Stockholm": { duration: "2h 0m" },
    "Berlin_Warsaw": { duration: "1h 30m" },
    "Berlin_Prague": { duration: "1h 0m" },
    "Berlin_Zurich": { duration: "1h 0m" },
    "Berlin_Brussels": { duration: "1h 15m" },
    "Berlin_Dubai": { duration: "6h 30m" },
    "Berlin_Istanbul": { duration: "3h 0m" },
    "Berlin_Athens": { duration: "3h 0m" },
    "Berlin_Oslo": { duration: "2h 0m" },
    "Berlin_Helsinki": { duration: "2h 30m" },

    "Madrid_Budapest": { duration: "2h 30m" },
    "Madrid_Debrecen": { duration: "3h 0m" },
    "Madrid_New York": { duration: "9h 0m" },
    "Madrid_London": { duration: "2h 15m" },
    "Madrid_Paris": { duration: "2h 0m" },
    "Madrid_Berlin": { duration: "2h 30m" },
    "Madrid_Los Angeles": { duration: "11h 0m" },
    "Madrid_Rome": { duration: "2h 0m" },
    "Madrid_Milan": { duration: "2h 0m" },
    "Madrid_Barcelona": { duration: "1h 45m" },
    "Madrid_Amsterdam": { duration: "2h 30m" },
    "Madrid_Vienna": { duration: "2h 30m" },
    "Madrid_Frankfurt": { duration: "2h 0m" },
    "Madrid_Lisbon": { duration: "1h 30m" },
    "Madrid_Copenhagen": { duration: "3h 0m" },
    "Madrid_Stockholm": { duration: "3h 0m" },
    "Madrid_Warsaw": { duration: "3h 0m" },
    "Madrid_Prague": { duration: "2h 30m" },
    "Madrid_Zurich": { duration: "2h 30m" },
    "Madrid_Brussels": { duration: "2h 0m" },
    "Madrid_Dubai": { duration: "6h 30m" },
    "Madrid_Istanbul": { duration: "3h 0m" },
    "Madrid_Athens": { duration: "3h 0m" },
    "Madrid_Oslo": { duration: "3h 0m" },
    "Madrid_Helsinki": { duration: "3h 30m" },

    "Los Angeles_Budapest": { duration: "13h 0m" },
    "Los Angeles_Debrecen": { duration: "13h 30m" },
    "Los Angeles_New York": { duration: "6h 0m" },
    "Los Angeles_London": { duration: "10h 0m" },
    "Los Angeles_Paris": { duration: "10h 0m" },
    "Los Angeles_Berlin": { duration: "10h 30m" },
    "Los Angeles_Madrid": { duration: "11h 0m" },
    "Los Angeles_Rome": { duration: "11h 0m" },
    "Los Angeles_Milan": { duration: "11h 0m" },
    "Los Angeles_Barcelona": { duration: "11h 0m" },
    "Los Angeles_Amsterdam": { duration: "11h 0m" },
    "Los Angeles_Vienna": { duration: "11h 0m" },
    "Los Angeles_Frankfurt": { duration: "11h 0m" },
    "Los Angeles_Lisbon": { duration: "11h 30m" },
    "Los Angeles_Copenhagen": { duration: "11h 30m" },
    "Los Angeles_Stockholm": { duration: "11h 30m" },
    "Los Angeles_Warsaw": { duration: "12h 0m" },
    "Los Angeles_Prague": { duration: "12h 0m" },
    "Los Angeles_Zurich": { duration: "11h 30m" },
    "Los Angeles_Brussels": { duration: "11h 0m" },
    "Los Angeles_Dubai": { duration: "16h 0m" },
    "Los Angeles_Istanbul": { duration: "13h 0m" },
    "Los Angeles_Athens": { duration: "13h 0m" },
    "Los Angeles_Oslo": { duration: "13h 0m" },
    "Los Angeles_Helsinki": { duration: "13h 30m" },

    "Rome_Budapest": { duration: "2h 0m" },
    "Rome_Debrecen": { duration: "2h 30m" },
    "Rome_New York": { duration: "9h 30m" },
    "Rome_London": { duration: "2h 30m" },
    "Rome_Paris": { duration: "2h 0m" },
    "Rome_Berlin": { duration: "2h 0m" },
    "Rome_Madrid": { duration: "2h 30m" },
    "Rome_Los Angeles": { duration: "12h 0m" },
    "Rome_Milan": { duration: "1h 30m" },
    "Rome_Barcelona": { duration: "2h 0m" },
    "Rome_Amsterdam": { duration: "2h 30m" },
    "Rome_Vienna": { duration: "1h 30m" },
    "Rome_Frankfurt": { duration: "2h 0m" },
    "Rome_Lisbon": { duration: "3h 0m" },
    "Rome_Copenhagen": { duration: "2h 30m" },
    "Rome_Stockholm": { duration: "3h 0m" },
    "Rome_Warsaw": { duration: "2h 30m" },
    "Rome_Prague": { duration: "1h 30m" },
    "Rome_Zurich": { duration: "1h 30m" },
    "Rome_Brussels": { duration: "2h 0m" },
    "Rome_Dubai": { duration: "6h 30m" },
    "Rome_Istanbul": { duration: "2h 30m" },
    "Rome_Athens": { duration: "2h 0m" },
    "Rome_Oslo": { duration: "3h 0m" },
    "Rome_Helsinki": { duration: "3h 0m" },
    "Milan_Budapest": { duration: "1h 30m" },
    "Milan_Debrecen": { duration: "2h 0m" },
    "Milan_New York": { duration: "10h 30m" },
    "Milan_London": { duration: "2h 0m" },
    "Milan_Paris": { duration: "1h 30m" },
    "Milan_Berlin": { duration: "1h 30m" },
    "Milan_Madrid": { duration: "2h 0m" },
    "Milan_Los Angeles": { duration: "12h 0m" },
    "Milan_Rome": { duration: "1h 0m" },
    "Milan_Barcelona": { duration: "1h 30m" },
    "Milan_Amsterdam": { duration: "2h 0m" },
    "Milan_Vienna": { duration: "1h 0m" },
    "Milan_Frankfurt": { duration: "1h 30m" },
    "Milan_Lisbon": { duration: "2h 30m" },
    "Milan_Copenhagen": { duration: "2h 0m" },
    "Milan_Stockholm": { duration: "2h 30m" },
    "Milan_Warsaw": { duration: "2h 0m" },
    "Milan_Prague": { duration: "1h 30m" },
    "Milan_Zurich": { duration: "1h 30m" },
    "Milan_Brussels": { duration: "1h 30m" },
    "Milan_Dubai": { duration: "6h 30m" },
    "Milan_Istanbul": { duration: "2h 30m" },
    "Milan_Athens": { duration: "2h 0m" },
    "Milan_Oslo": { duration: "2h 30m" },
    "Milan_Helsinki": { duration: "3h 0m" },

    "Barcelona_Budapest": { duration: "2h 30m" },
    "Barcelona_Debrecen": { duration: "2h 45m" },
    "Barcelona_New York": { duration: "10h 0m" },
    "Barcelona_London": { duration: "2h 0m" },
    "Barcelona_Paris": { duration: "2h 0m" },
    "Barcelona_Berlin": { duration: "2h 30m" },
    "Barcelona_Madrid": { duration: "1h 30m" },
    "Barcelona_Los Angeles": { duration: "12h 30m" },
    "Barcelona_Rome": { duration: "2h 0m" },
    "Barcelona_Milan": { duration: "1h 30m" },
    "Barcelona_Amsterdam": { duration: "2h 30m" },
    "Barcelona_Vienna": { duration: "2h 0m" },
    "Barcelona_Frankfurt": { duration: "2h 30m" },
    "Barcelona_Lisbon": { duration: "2h 30m" },
    "Barcelona_Copenhagen": { duration: "2h 30m" },
    "Barcelona_Stockholm": { duration: "3h 0m" },
    "Barcelona_Warsaw": { duration: "3h 0m" },
    "Barcelona_Prague": { duration: "2h 30m" },
    "Barcelona_Zurich": { duration: "2h 30m" },
    "Barcelona_Brussels": { duration: "2h 30m" },
    "Barcelona_Dubai": { duration: "6h 30m" },
    "Barcelona_Istanbul": { duration: "3h 0m" },
    "Barcelona_Athens": { duration: "3h 0m" },
    "Barcelona_Oslo": { duration: "3h 0m" },
    "Barcelona_Helsinki": { duration: "3h 30m" },

    "Amsterdam_Budapest": { duration: "2h 30m" },
    "Amsterdam_Debrecen": { duration: "2h 45m" },
    "Amsterdam_New York": { duration: "10h 0m" },
    "Amsterdam_London": { duration: "1h 30m" },
    "Amsterdam_Paris": { duration: "1h 30m" },
    "Amsterdam_Berlin": { duration: "1h 45m" },
    "Amsterdam_Madrid": { duration: "2h 0m" },
    "Amsterdam_Los Angeles": { duration: "11h 30m" },
    "Amsterdam_Rome": { duration: "2h 0m" },
    "Amsterdam_Milan": { duration: "1h 45m" },
    "Amsterdam_Barcelona": { duration: "2h 0m" },
    "Amsterdam_Vienna": { duration: "2h 0m" },
    "Amsterdam_Frankfurt": { duration: "1h 30m" },
    "Amsterdam_Lisbon": { duration: "2h 30m" },
    "Amsterdam_Copenhagen": { duration: "2h 0m" },
    "Amsterdam_Stockholm": { duration: "2h 30m" },
    "Amsterdam_Warsaw": { duration: "2h 30m" },
    "Amsterdam_Prague": { duration: "2h 0m" },
    "Amsterdam_Zurich": { duration: "1h 45m" },
    "Amsterdam_Brussels": { duration: "1h 30m" },
    "Amsterdam_Dubai": { duration: "6h 30m" },
    "Amsterdam_Istanbul": { duration: "3h 0m" },
    "Amsterdam_Athens": { duration: "3h 0m" },
    "Amsterdam_Oslo": { duration: "2h 0m" },
    "Amsterdam_Helsinki": { duration: "2h 30m" },

    "Vienna_Budapest": { duration: "1h 0m" },
    "Vienna_Debrecen": { duration: "1h 30m" },
    "Vienna_New York": { duration: "10h 30m" },
    "Vienna_London": { duration: "2h 0m" },
    "Vienna_Paris": { duration: "2h 0m" },
    "Vienna_Berlin": { duration: "1h 30m" },
    "Vienna_Madrid": { duration: "2h 30m" },
    "Vienna_Los Angeles": { duration: "11h 30m" },
    "Vienna_Rome": { duration: "1h 45m" },
    "Vienna_Milan": { duration: "1h 30m" },
    "Vienna_Barcelona": { duration: "2h 30m" },
    "Vienna_Amsterdam": { duration: "2h 0m" },
    "Vienna_Frankfurt": { duration: "1h 30m" },
    "Vienna_Lisbon": { duration: "3h 0m" },
    "Vienna_Copenhagen": { duration: "2h 0m" },
    "Vienna_Stockholm": { duration: "2h 30m" },
    "Vienna_Warsaw": { duration: "1h 30m" },
    "Vienna_Prague": { duration: "1h 30m" },
    "Vienna_Zurich": { duration: "1h 30m" },
    "Vienna_Brussels": { duration: "1h 30m" },
    "Vienna_Dubai": { duration: "6h 0m" },
    "Vienna_Istanbul": { duration: "2h 30m" },
    "Vienna_Athens": { duration: "2h 30m" },
    "Vienna_Oslo": { duration: "2h 0m" },
    "Vienna_Helsinki": { duration: "2h 30m" },

    "Frankfurt_Budapest": { duration: "2h 0m" },
    "Frankfurt_Debrecen": { duration: "2h 0m" },
    "Frankfurt_New York": { duration: "9h 30m" },
    "Frankfurt_London": { duration: "1h 45m" },
    "Frankfurt_Paris": { duration: "1h 45m" },
    "Frankfurt_Berlin": { duration: "1h 30m" },
    "Frankfurt_Madrid": { duration: "2h 30m" },
    "Frankfurt_Los Angeles": { duration: "11h 0m" },
    "Frankfurt_Rome": { duration: "2h 0m" },
    "Frankfurt_Milan": { duration: "1h 30m" },
    "Frankfurt_Barcelona": { duration: "2h 30m" },
    "Frankfurt_Amsterdam": { duration: "1h 30m" },
    "Frankfurt_Vienna": { duration: "1h 30m" },
    "Frankfurt_Lisbon": { duration: "3h 0m" },
    "Frankfurt_Copenhagen": { duration: "1h 45m" },
    "Frankfurt_Stockholm": { duration: "2h 30m" },
    "Frankfurt_Warsaw": { duration: "1h 30m" },
    "Frankfurt_Prague": { duration: "1h 30m" },
    "Frankfurt_Zurich": { duration: "1h 0m" },
    "Frankfurt_Brussels": { duration: "1h 30m" },
    "Frankfurt_Dubai": { duration: "6h 30m" },
    "Frankfurt_Istanbul": { duration: "3h 0m" },
    "Frankfurt_Athens": { duration: "2h 30m" },
    "Frankfurt_Oslo": { duration: "2h 0m" },
    "Frankfurt_Helsinki": { duration: "2h 30m" },


        "Lisbon_Budapest": { duration: "3h 30m" },
        "Lisbon_Debrecen": { duration: "3h 45m" },
        "Lisbon_New York": { duration: "8h 0m" },
        "Lisbon_London": { duration: "2h 30m" },
        "Lisbon_Paris": { duration: "2h 15m" },
        "Lisbon_Berlin": { duration: "3h 15m" },
        "Lisbon_Madrid": { duration: "1h 15m" },
        "Lisbon_Los Angeles": { duration: "11h 30m" },
        "Lisbon_Rome": { duration: "3h 0m" },
        "Lisbon_Milan": { duration: "2h 45m" },
        "Lisbon_Barcelona": { duration: "1h 45m" },
        "Lisbon_Amsterdam": { duration: "2h 45m" },
        "Lisbon_Vienna": { duration: "3h 15m" },
        "Lisbon_Frankfurt": { duration: "3h 0m" },
        "Lisbon_Copenhagen": { duration: "3h 45m" },
        "Lisbon_Stockholm": { duration: "4h 0m" },
        "Lisbon_Warsaw": { duration: "4h 15m" },
        "Lisbon_Prague": { duration: "3h 30m" },
        "Lisbon_Zurich": { duration: "2h 45m" },
        "Lisbon_Brussels": { duration: "2h 45m" },
        "Lisbon_Dubai": { duration: "7h 30m" },
        "Lisbon_Istanbul": { duration: "4h 15m" },
        "Lisbon_Athens": { duration: "4h 30m" },
        "Lisbon_Oslo": { duration: "4h 0m" },
        "Lisbon_Helsinki": { duration: "4h 30m" },

    

        "Copenhagen_Budapest": { duration: "2h 0m" },
        "Copenhagen_Debrecen": { duration: "2h 15m" },
        "Copenhagen_New York": { duration: "8h 30m" },
        "Copenhagen_London": { duration: "1h 45m" },
        "Copenhagen_Paris": { duration: "2h 0m" },
        "Copenhagen_Berlin": { duration: "1h 0m" },
        "Copenhagen_Madrid": { duration: "3h 0m" },
        "Copenhagen_Los Angeles": { duration: "11h 15m" },
        "Copenhagen_Rome": { duration: "2h 30m" },
        "Copenhagen_Milan": { duration: "2h 15m" },
        "Copenhagen_Barcelona": { duration: "3h 0m" },
        "Copenhagen_Amsterdam": { duration: "1h 30m" },
        "Copenhagen_Vienna": { duration: "1h 45m" },
        "Copenhagen_Frankfurt": { duration: "1h 30m" },
        "Copenhagen_Lisbon": { duration: "3h 45m" },
        "Copenhagen_Stockholm": { duration: "1h 0m" },
        "Copenhagen_Warsaw": { duration: "1h 30m" },
        "Copenhagen_Prague": { duration: "1h 30m" },
        "Copenhagen_Zurich": { duration: "1h 45m" },
        "Copenhagen_Brussels": { duration: "1h 45m" },
        "Copenhagen_Dubai": { duration: "6h 30m" },
        "Copenhagen_Istanbul": { duration: "3h 15m" },
        "Copenhagen_Athens": { duration: "3h 30m" },
        "Copenhagen_Oslo": { duration: "1h 0m" },
        "Copenhagen_Helsinki": { duration: "1h 30m" },
        "Stockholm_Budapest": { duration: "2h 15m" },
        "Stockholm_Debrecen": { duration: "2h 30m" },
        "Stockholm_New York": { duration: "8h 15m" },
        "Stockholm_London": { duration: "2h 30m" },
        "Stockholm_Paris": { duration: "2h 45m" },
        "Stockholm_Berlin": { duration: "1h 45m" },
        "Stockholm_Madrid": { duration: "3h 30m" },
        "Stockholm_Los Angeles": { duration: "11h 0m" },
        "Stockholm_Rome": { duration: "3h 0m" },
        "Stockholm_Milan": { duration: "2h 45m" },
        "Stockholm_Barcelona": { duration: "3h 15m" },
        "Stockholm_Amsterdam": { duration: "2h 0m" },
        "Stockholm_Vienna": { duration: "2h 15m" },
        "Stockholm_Frankfurt": { duration: "2h 0m" },
        "Stockholm_Lisbon": { duration: "4h 0m" },
        "Stockholm_Copenhagen": { duration: "1h 15m" },
        "Stockholm_Warsaw": { duration: "1h 45m" },
        "Stockholm_Prague": { duration: "2h 0m" },
        "Stockholm_Zurich": { duration: "2h 15m" },
        "Stockholm_Brussels": { duration: "2h 15m" },
        "Stockholm_Dubai": { duration: "6h 30m" },
        "Stockholm_Istanbul": { duration: "3h 45m" },
        "Stockholm_Athens": { duration: "3h 45m" },
        "Stockholm_Oslo": { duration: "1h 0m" },
        "Stockholm_Helsinki": { duration: "1h 0m" },

        "Warsaw_Budapest": { duration: "1h 15m" },
        "Warsaw_Debrecen": { duration: "1h 30m" },
        "Warsaw_New York": { duration: "9h 30m" },
        "Warsaw_London": { duration: "2h 30m" },
        "Warsaw_Paris": { duration: "2h 45m" },
        "Warsaw_Berlin": { duration: "1h 20m" },
        "Warsaw_Madrid": { duration: "3h 30m" },
        "Warsaw_Los Angeles": { duration: "12h 0m" },
        "Warsaw_Rome": { duration: "2h 30m" },
        "Warsaw_Milan": { duration: "2h 15m" },
        "Warsaw_Barcelona": { duration: "3h 15m" },
        "Warsaw_Amsterdam": { duration: "2h 0m" },
        "Warsaw_Vienna": { duration: "1h 15m" },
        "Warsaw_Frankfurt": { duration: "1h 30m" },
        "Warsaw_Lisbon": { duration: "4h 0m" },
        "Warsaw_Copenhagen": { duration: "1h 30m" },
        "Warsaw_Stockholm": { duration: "1h 40m" },
        "Warsaw_Prague": { duration: "1h 15m" },
        "Warsaw_Zurich": { duration: "2h 0m" },
        "Warsaw_Brussels": { duration: "2h 0m" },
        "Warsaw_Dubai": { duration: "6h 15m" },
        "Warsaw_Istanbul": { duration: "2h 30m" },
        "Warsaw_Athens": { duration: "2h 45m" },
        "Warsaw_Oslo": { duration: "1h 50m" },
        "Warsaw_Helsinki": { duration: "1h 45m" },

        "Prague_Budapest": { duration: "1h 15m" },
        "Prague_Debrecen": { duration: "1h 30m" },
        "Prague_New York": { duration: "9h 15m" },
        "Prague_London": { duration: "2h 0m" },
        "Prague_Paris": { duration: "1h 45m" },
        "Prague_Berlin": { duration: "1h 10m" },
        "Prague_Madrid": { duration: "3h 0m" },
        "Prague_Los Angeles": { duration: "12h 0m" },
        "Prague_Rome": { duration: "1h 45m" },
        "Prague_Milan": { duration: "1h 30m" },
        "Prague_Barcelona": { duration: "2h 30m" },
        "Prague_Amsterdam": { duration: "1h 30m" },
        "Prague_Vienna": { duration: "1h 0m" },
        "Prague_Frankfurt": { duration: "1h 10m" },
        "Prague_Lisbon": { duration: "3h 30m" },
        "Prague_Copenhagen": { duration: "1h 30m" },
        "Prague_Stockholm": { duration: "2h 0m" },
        "Prague_Warsaw": { duration: "1h 15m" },
        "Prague_Zurich": { duration: "1h 30m" },
        "Prague_Brussels": { duration: "1h 30m" },
        "Prague_Dubai": { duration: "6h 15m" },
        "Prague_Istanbul": { duration: "2h 15m" },
        "Prague_Athens": { duration: "2h 30m" },
        "Prague_Oslo": { duration: "2h 0m" },
        "Prague_Helsinki": { duration: "2h 15m" },

        "Zurich_Budapest": { "duration": "1h 40m" },
        "Zurich_Debrecen": { "duration": "1h 50m" },
        "Zurich_New York": { "duration": "8h 20m" },
        "Zurich_London": { "duration": "1h 45m" },
        "Zurich_Paris": { "duration": "1h 15m" },
        "Zurich_Berlin": { "duration": "1h 30m" },
        "Zurich_Madrid": { "duration": "2h 30m" },
        "Zurich_Los Angeles": { "duration": "12h 30m" },
        "Zurich_Rome": { "duration": "1h 30m" },
        "Zurich_Milan": { "duration": "1h 0m" },
        "Zurich_Barcelona": { "duration": "1h 50m" },
        "Zurich_Amsterdam": { "duration": "1h 30m" },
        "Zurich_Vienna": { "duration": "1h 20m" },
        "Zurich_Frankfurt": { "duration": "1h 0m" },
        "Zurich_Lisbon": { "duration": "2h 45m" },
        "Zurich_Copenhagen": { "duration": "1h 45m" },
        "Zurich_Stockholm": { "duration": "2h 15m" },
        "Zurich_Warsaw": { "duration": "1h 55m" },
        "Zurich_Prague": { "duration": "1h 10m" },
        "Zurich_Brussels": { "duration": "1h 15m" },
        "Zurich_Dubai": { "duration": "6h 10m" },
        "Zurich_Istanbul": { "duration": "2h 50m" },
        "Zurich_Athens": { "duration": "2h 35m" },
        "Zurich_Oslo": { "duration": "2h 15m" },
        "Zurich_Helsinki": { "duration": "2h 45m" },

        "Brussels_Budapest": { "duration": "2h 0m" },
        "Brussels_Debrecen": { "duration": "2h 10m" },
        "Brussels_New York": { "duration": "8h 15m" },
        "Brussels_London": { "duration": "1h 0m" },
        "Brussels_Paris": { "duration": "1h 10m" },
        "Brussels_Berlin": { "duration": "1h 20m" },
        "Brussels_Madrid": { "duration": "2h 20m" },
        "Brussels_Los Angeles": { "duration": "12h 15m" },
        "Brussels_Rome": { "duration": "2h 10m" },
        "Brussels_Milan": { "duration": "1h 30m" },
        "Brussels_Barcelona": { "duration": "2h 0m" },
        "Brussels_Amsterdam": { "duration": "0h 50m" },
        "Brussels_Vienna": { "duration": "1h 40m" },
        "Brussels_Frankfurt": { "duration": "1h 0m" },
        "Brussels_Lisbon": { "duration": "2h 40m" },
        "Brussels_Copenhagen": { "duration": "1h 30m" },
        "Brussels_Stockholm": { "duration": "2h 10m" },
        "Brussels_Warsaw": { "duration": "2h 5m" },
        "Brussels_Prague": { "duration": "1h 35m" },
        "Brussels_Zurich": { "duration": "1h 15m" },
        "Brussels_Dubai": { "duration": "6h 50m" },
        "Brussels_Istanbul": { "duration": "3h 0m" },
        "Brussels_Athens": { "duration": "3h 10m" },
        "Brussels_Oslo": { "duration": "2h 0m" },
        "Brussels_Helsinki": { "duration": "2h 30m" },

        "Dubai_Budapest": { "duration": "6h 30m" },
        "Dubai_Debrecen": { "duration": "6h 40m" },
        "Dubai_New York": { "duration": "14h 0m" },
        "Dubai_London": { "duration": "7h 15m" },
        "Dubai_Paris": { "duration": "7h 0m" },
        "Dubai_Berlin": { "duration": "6h 50m" },
        "Dubai_Madrid": { "duration": "7h 20m" },
        "Dubai_Los Angeles": { "duration": "16h 0m" },
        "Dubai_Rome": { "duration": "6h 30m" },
        "Dubai_Milan": { "duration": "6h 30m" },
        "Dubai_Barcelona": { "duration": "7h 10m" },
        "Dubai_Amsterdam": { "duration": "7h 10m" },
        "Dubai_Vienna": { "duration": "6h 40m" },
        "Dubai_Frankfurt": { "duration": "6h 40m" },
        "Dubai_Lisbon": { "duration": "7h 40m" },
        "Dubai_Copenhagen": { "duration": "7h 0m" },
        "Dubai_Stockholm": { "duration": "7h 30m" },
        "Dubai_Warsaw": { "duration": "6h 40m" },
        "Dubai_Prague": { "duration": "6h 30m" },
        "Dubai_Zurich": { "duration": "6h 40m" },
        "Dubai_Brussels": { "duration": "7h 0m" },
        "Dubai_Istanbul": { "duration": "4h 30m" },
        "Dubai_Athens": { "duration": "5h 10m" },
        "Dubai_Oslo": { "duration": "7h 0m" },
        "Dubai_Helsinki": { "duration": "7h 10m" },

        "Istanbul_Budapest": { "duration": "2h 10m" },
        "Istanbul_Debrecen": { "duration": "2h 10m" },
        "Istanbul_New York": { "duration": "11h 0m" },
        "Istanbul_London": { "duration": "3h 50m" },
        "Istanbul_Paris": { "duration": "3h 10m" },
        "Istanbul_Berlin": { "duration": "3h 10m" },
        "Istanbul_Madrid": { "duration": "3h 20m" },
        "Istanbul_Los Angeles": { "duration": "13h 0m" },
        "Istanbul_Rome": { "duration": "2h 30m" },
        "Istanbul_Milan": { "duration": "2h 30m" },
        "Istanbul_Barcelona": { "duration": "3h 10m" },
        "Istanbul_Amsterdam": { "duration": "3h 10m" },
        "Istanbul_Vienna": { "duration": "2h 30m" },
        "Istanbul_Frankfurt": { "duration": "3h 0m" },
        "Istanbul_Lisbon": { "duration": "4h 0m" },
        "Istanbul_Copenhagen": { "duration": "3h 0m" },
        "Istanbul_Stockholm": { "duration": "3h 20m" },
        "Istanbul_Warsaw": { "duration": "2h 30m" },
        "Istanbul_Prague": { "duration": "2h 30m" },
        "Istanbul_Zurich": { "duration": "3h 0m" },
        "Istanbul_Brussels": { "duration": "3h 0m" },
        "Istanbul_Dubai": { "duration": "4h 30m" },
        "Istanbul_Athens": { "duration": "1h 30m" },
        "Istanbul_Oslo": { "duration": "3h 20m" },
        "Istanbul_Helsinki": { "duration": "3h 10m" },

        "Athens_Budapest": { "duration": "2h 0m" },
        "Athens_Debrecen": { "duration": "2h 0m" },
        "Athens_New York": { "duration": "11h 0m" },
        "Athens_London": { "duration": "3h 0m" },
        "Athens_Paris": { "duration": "3h 0m" },
        "Athens_Berlin": { "duration": "3h 0m" },
        "Athens_Madrid": { "duration": "3h 10m" },
        "Athens_Los Angeles": { "duration": "12h 30m" },
        "Athens_Rome": { "duration": "2h 0m" },
        "Athens_Milan": { "duration": "2h 0m" },
        "Athens_Barcelona": { "duration": "3h 0m" },
        "Athens_Amsterdam": { "duration": "3h 0m" },
        "Athens_Vienna": { "duration": "2h 0m" },
        "Athens_Frankfurt": { "duration": "3h 0m" },
        "Athens_Lisbon": { "duration": "3h 30m" },
        "Athens_Copenhagen": { "duration": "3h 0m" },
        "Athens_Stockholm": { "duration": "3h 20m" },
        "Athens_Warsaw": { "duration": "2h 30m" },
        "Athens_Prague": { "duration": "2h 30m" },
        "Athens_Zurich": { "duration": "2h 30m" },
        "Athens_Brussels": { "duration": "3h 0m" },
        "Athens_Dubai": { "duration": "5h 30m" },
        "Athens_Istanbul": { "duration": "1h 30m" },
        "Athens_Oslo": { "duration": "3h 10m" },
        "Athens_Helsinki": { "duration": "3h 0m" },

        "Oslo_Budapest": { "duration": "2h 30m" },
        "Oslo_Debrecen": { "duration": "2h 30m" },
        "Oslo_New York": { "duration": "8h 30m" },
        "Oslo_London": { "duration": "2h 0m" },
        "Oslo_Paris": { "duration": "2h 10m" },
        "Oslo_Berlin": { "duration": "1h 50m" },
        "Oslo_Madrid": { "duration": "3h 10m" },
        "Oslo_Los Angeles": { "duration": "11h 0m" },
        "Oslo_Rome": { "duration": "2h 30m" },
        "Oslo_Milan": { "duration": "2h 30m" },
        "Oslo_Barcelona": { "duration": "3h 0m" },
        "Oslo_Amsterdam": { "duration": "1h 45m" },
        "Oslo_Vienna": { "duration": "2h 0m" },
        "Oslo_Frankfurt": { "duration": "1h 45m" },
        "Oslo_Lisbon": { "duration": "3h 10m" },
        "Oslo_Copenhagen": { "duration": "1h 0m" },
        "Oslo_Stockholm": { "duration": "1h 10m" },
        "Oslo_Warsaw": { "duration": "2h 0m" },
        "Oslo_Prague": { "duration": "2h 0m" },
        "Oslo_Zurich": { "duration": "2h 0m" },
        "Oslo_Brussels": { "duration": "2h 0m" },
        "Oslo_Dubai": { "duration": "6h 30m" },
        "Oslo_Istanbul": { "duration": "3h 0m" },
        "Oslo_Athens": { "duration": "3h 10m" },
        "Oslo_Helsinki": { "duration": "1h 30m" },

        "Helsinki_Budapest": { "duration": "2h 30m" },
        "Helsinki_Debrecen": { "duration": "2h 30m" },
        "Helsinki_New York": { "duration": "9h 30m" },
        "Helsinki_London": { "duration": "3h 0m" },
        "Helsinki_Paris": { "duration": "3h 0m" },
        "Helsinki_Berlin": { "duration": "2h 0m" },
        "Helsinki_Madrid": { "duration": "4h 0m" },
        "Helsinki_Los Angeles": { "duration": "12h 0m" },
        "Helsinki_Rome": { "duration": "3h 0m" },
        "Helsinki_Milan": { "duration": "3h 0m" },
        "Helsinki_Barcelona": { "duration": "3h 30m" },
        "Helsinki_Amsterdam": { "duration": "2h 30m" },
        "Helsinki_Vienna": { "duration": "2h 30m" },
        "Helsinki_Frankfurt": { "duration": "2h 30m" },
        "Helsinki_Lisbon": { "duration": "4h 0m" },
        "Helsinki_Copenhagen": { "duration": "1h 30m" },
        "Helsinki_Stockholm": { "duration": "1h 0m" },
        "Helsinki_Warsaw": { "duration": "2h 0m" },
        "Helsinki_Prague": { "duration": "2h 0m" },
        "Helsinki_Zurich": { "duration": "2h 30m" },
        "Helsinki_Brussels": { "duration": "2h 30m" },
        "Helsinki_Dubai": { "duration": "6h 0m" },
        "Helsinki_Istanbul": { "duration": "3h 0m" },
        "Helsinki_Athens": { "duration": "3h 30m" },
        "Helsinki_Oslo": { "duration": "1h 30m" }
};

const searchButton = document.getElementById("searchButton");
const resultsDiv = document.getElementById("results");

searchButton.addEventListener("click", () => {
    const departure = departureSelect.value;
    const arrival = arrivalSelect.value;
    const route = `${departure}_${arrival}`;

    if (flightData[route]) {
        const flightInfo = flightData[route];
        const resultBox = document.createElement("div");
        resultBox.classList.add("result-box");
        resultBox.innerHTML = `
            <p><strong>Időtartam:</strong> ${flightInfo.duration}</p>
            <button class="btn btn-primary show-more">Tovább</button>
        `;
        resultsDiv.innerHTML = ''; // Clear previous results
        resultsDiv.appendChild(resultBox);

        // Add event listener to the "Tovább" button
        const showMoreButton = resultBox.querySelector(".show-more");
        showMoreButton.addEventListener("click", () => {
            displayMoreOffers();
        });
    } else {
        resultsDiv.innerHTML = '<p>Ez az útvonal nem elérhető.</p>';
    }
});

function displayMoreOffers() {
    const additionalOffers = [
        {
            title: "QATAR AIRWAYS",
            description: "A Qatar Airways ezt ajánlja neked!",
            price: "50,000 HUF"
        },
        {
            title: "TURKISH AIRLINES",
            description: "A Turkish Airlines ezt ajánlja neked!",
            price: "55,000 HUF"
        },
        {
            title: "EMIRATES",
            description: "Az Emirates ezt ajánlja neked!",
            price: "45,000 HUF"
        }
    ];

    const offersDiv = document.createElement("div");
    offersDiv.classList.add("additional-offers");

    additionalOffers.forEach(offer => {
        const offerBox = document.createElement("div");
        offerBox.classList.add("result-box");
        offerBox.innerHTML = `
            <h4>${offer.title}</h4>
            <p>${offer.description}</p>
            <p><strong>Ár:</strong> ${offer.price}</p>
        `;
        offersDiv.appendChild(offerBox);
    });

    resultsDiv.appendChild(offersDiv);
}

